### ISSUE TITLE
Problem: No RedHat/CentOS support for cadence

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-enduro#1]
The role's meta says it supports RH/CentOS but the task to install cadence is:

```
- name: "Add cadence repository"
  apt_repository:
    repo: "deb [trusted=yes] https://jenkins-ci.archivematica.org/repos/am-packbuild/cadence/bionic/ ./"
    state: present
```
