### ISSUE TITLE
Problem: The role fails when database is not located in localhost

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-enduro#3]
The role fails when database is not located in localhost

**Comment by mamedin** [comment]
Using the following variables on mysqldb tasks fixes the issue:

* `login_host`
* `login_password`
* `login_user`

**Comment by mamedin** [comment]
For instance:

```
    - name: "Populate cadence database"
      mysql_db:
        name: "{{ cadence_db_name }}"
        state: import
        target: "{{ item }}"
        login_host: "{{ cadence_db_host }}"
        login_user: "{{ cadence_db_user }}"
        login_password: "{{ cadence_db_pass }}"
      with_items:
        - /usr/share/cadence/migrations/cadence-migrations/v0.1/base.sql
      ignore_errors: true
```
